mqtt:
  host: 192.168.1.128

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/101
          roles:
            - detect
            - rtmp
    detect:
      fps: 2

  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/302
          roles:
            - detect
            - rtmp

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m