mqtt:
  host: 192.168.1.128

cameras:
  cam1:
    ffmpeg:
      input_args:
      - -avoid_negative_ts
      - make_zero
      - -fflags
      - nobuffer+genpts+discardcorrupt
      - -flags
      - low_delay
      - -strict
      - experimental
      - -analyzeduration
      - 1000M
      - -probesize
      - 1000M
      - -rw_timeout
      - "5000000"
      inputs:
        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/101
          roles:
            - detect
            - rtmp
    detect:
      fps: 5

#  cam2:
#    ffmpeg:
#      inputs:
#        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/302
#          roles:
#            - detect
#            - rtmp

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m