mqtt:
  host: 192.168.1.128

detect:
  enabled: True
  width: 1080
  height: 960
  fps: 1
  max_disappeared: 5

snapshots:
  enabled: True
  bounding_box: True

rtmp:
  enabled: False

record:
  enabled: True
  events:
    pre_capture: 10
    post_capture: 10

birdseye:
  enabled: False

logger:
  default: debug

detectors:
  cpu1:
    type: cpu
    num_threads: 3

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/102
          roles:
            - detect
        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/101
          roles:
            - record

  cam2:
    ffmpeg:
      inputs:
        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/302
          roles:
            - detect
            - record

#ffmpeg:
#  hwaccel_args:
#    - -c:v
#    - h264_v4l2m2m

#ffmpeg:
#  hwaccel_args:
#    - -c:v
#    - h264_mmal

#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p