mqtt:
  host: 192.168.1.118

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/101
          roles:
            - detect
    detect:
      fps: 1

#  cam2:
#    ffmpeg:
#      inputs:
#        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/302
#          roles:
#            - detect
#            - rtmp

#ffmpeg:
#  hwaccel_args:
#    - -c:v
#    - h264_v4l2m2m

#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p