mqtt:
  host: 192.168.1.128

detect:
  width: 960
  height: 1080
  fps: 2


rtmp:
  enabled: False

logger:
  default: debug

detectors:
  cpu1:
    type: cpu
    num_threads: 3

cameras:
  cam1:
    ffmpeg:
      inputs:
        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/101
          roles:
            - detect

#  cam2:
#    ffmpeg:
#      inputs:
#        - path: rtsp://admin:nelis342256@192.168.1.144:554/Streaming/Channels/301
#          roles:
#            - detect

ffmpeg:
  hwaccel_args:
    - -c:v
    - h264_v4l2m2m

#ffmpeg:
#  hwaccel_args:
#    - -c:v
#    - h264_mmal

#ffmpeg:
#  hwaccel_args:
#    - -hwaccel
#    - vaapi
#    - -hwaccel_device
#    - /dev/dri/renderD128
#    - -hwaccel_output_format
#    - yuv420p